version: '3'
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-app
    volumes:
      - progresDB:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PGDATA: /var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432'
  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
volumes:
  progresDB:
